### ISSUE TITLE
requiring non null values

### ISSUE THREAD

**Issue by jeffreycwitt** [semantic-integration/hypergraphql#21]
I've got things up and running and now I'm looking into more advanced queries

For example, I'm reading graphql docs and http://graphql.org/learn/schema/#lists-and-non-null and it looks like I should be able to add an `!` to exclude null return values: 

So I tried:

```
type Expression @service(id:"scta-sparql") {
    questionTitle: String! @service(id:"scta-sparql")
}
```

And this reports: 

`graphql.language.NonNullType cannot be cast to graphql.language.ListType`

It seems to me the added the `!` should change the SPARQL Query from something like this

```
SELECT * WHERE { { SELECT ?x_1 WHERE { ?x_1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://scta.info/resource/expression> .  } LIMIT 100  }  OPTIONAL { ?x_1 <http://scta.info/property/questionTitle> ?x_1_1 .  }  }
```
to 

```
SELECT * WHERE { { SELECT ?x_1 WHERE { ?x_1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://scta.info/resource/expression> .  } LIMIT 100  }   ?x_1 <http://scta.info/property/questionTitle> ?x_1_1 .   }
```

Is this feature not-yet implemented or am I missing something?

Seems like we could implement it if we duplicated [`optionalStr`](https://github.com/semantic-integration/hypergraphql/blob/master/src/main/java/org/hypergraphql/query/converters/SPARQLServiceConverter.java#L29) and then modified it to nonNullSTR:

    private String nonNullSTR(String sparqlPattern) {
        final String PATTERN = " %s ";
        return String.format(PATTERN, sparqlPattern);
    }

and then [`getFieldSubQuery()`](https://github.com/semantic-integration/hypergraphql/blob/master/src/main/java/org/hypergraphql/query/converters/SPARQLServiceConverter.java#L198) would need to recognize the `!` and choose `nonNullStr()` in [ln 221](https://github.com/semantic-integration/hypergraphql/blob/master/src/main/java/org/hypergraphql/query/converters/SPARQLServiceConverter.java#L221) rather than `optionalStr()`

**Comment by sklarman** [comment]
Hi, 

Seems it was a bug. I just pushed a commit to the `master` branch which should fix it. 

Note that `NonNullType` modifiers do not affect the underlying SPARQL queries. A SPARQL query just returns the relevant (complete or incomplete) portion of RDF data from the endpoint, which only then is processed locally by GraphQL fetchers in order to create and validate answers. So it's in this latter stage when GraphQL will recognize that a `NonNullType` value is actually missing and will report a suitable execution exception.
